version: '3'

services:
  app-vue:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: tutorias_front
    container_name: tutorias_front
    env_file:
      - .env
    ports:
    - "8001:80"

